### ISSUE TITLE
NoMethodError: undefined method `available?'

### ISSUE THREAD

**Issue by elfassy** [bensie/enom#1]
NoMethodError: undefined method `available?' for Enom::Domain:Class

It seems this method is not working, all others work ok.

**Comment by bensie** [comment]
This method was added in d7e814f4db94fef063e09d39b3c63f612c9e9fc0 and apparently I never released a gem version after adding it.  Will release one ASAP -- thanks for pointing this out!

You can use `Enom::Domain.check(name) == "available"` in the meantime.
