### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by ghost** [bensie/enom#12]
Problem: Trying out the examples always results in the following errors.

2.0.0p247 :002 > require 'Enom'
 => true
2.0.0p247 :003 > Enom::Client.username = 'asdf'
NoMethodError: undefined method `username=' for Enom::Client:Class
    from (irb):3
    from /Users/marcello/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.14/lib/rails/commands/console.rb:47:in`start'
    from /Users/marcello/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.14/lib/rails/commands/console.rb:8:in `start'
    from /Users/marcello/.rvm/gems/ruby-2.0.0-p247/gems/railties-3.2.14/lib/rails/commands.rb:41:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'
2.0.0p247 :004 >

Trying it from the app results in same error
undefined method `username=' for Enom::Client:Class

Versions:
gem 'rails', '3.2.14'
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.4.0]
Using enom (0.0.1)

**Comment by bensie** [comment]
Please update to the latest version of the gem (1.1.2).

**Comment by ghost** [comment]
Ok looks like that did the trick. Thanks for the quick response.
