### ISSUE TITLE
Invalid Registrant information., Zipcode was invalid for that country.

### ISSUE THREAD

**Issue by alfmacedo** [bensie/enom#13]
Hello. 
I'm using rails 4.1 and gem "enom 1.1.2".

I have a problem registering a domain: 

Enom::Domain.register!("example.com", "RegistrantFirstName" => "Test", "RegistrantLastName" => "Tester", "RegistrantCountry" => "PE", "RegistrantPostalCode" => "CALLAO 36", "AuxBillingPostalCode" => "CALLAO 36", "TechPostalCode" => "CALLAO 36", "AdminPostalCode" => "CALLAO 36", "BillingPostalCode" => "CALLAO 36")
## => "Invalid Registrant information., Zipcode was invalid for that country. Sample format: CALLAO 0, Invalid Aux Billing information., Zipcode was invalid for that country. Sample format: CALLAO 0, Invalid Administrative information., Zipcode was invalid for that country. Sample format: CALLAO 0, Invalid Technical information., Zipcode was invalid for that country. Sample format: CALLAO 0"

Thanks.

**Comment by bensie** [comment]
Are you able to register the domain successfully using that zip code from their web interface?

**Comment by alfmacedo** [comment]
Thanks . Yes, i can.

**Comment by alfmacedo** [comment]
Sorry. It was a problem with my account settings (eNom.com)
