### ISSUE TITLE
strange check results

### ISSUE THREAD

**Issue by elfassy** [bensie/enom#2]
I get the following as available when clearly they are not:

internet.info
internet.mobi
internet.cc
internet.me

I think this might be more of a problem with the enom API.

any thoughts?
Thanks!

**Comment by bensie** [comment]
Are you using the test API?  I've seen weird results from there.

I just ran a check against the live API for those domains and all came back as unavailable.

**Comment by elfassy** [comment]
Good call, I was indeed using the test api. You are right it works perfectly with the live API. Thanks!
